helmDefaults:
  wait: false
  timeout: 900

environments:
  default:
    values:
    - helmfile_secrets.yaml
  createns:

releases:
- name: simple-cm
  chart: ./simple-cm
  wait: true
  namespace: "sandbox"


- name: chaoskube
  chart: stable/chaoskube
  wait: true
  namespace: sandbox
  values:
  - dryRun: true
  - namespaces: 'sandbox'



